### ISSUE TITLE
Error response from daemon: Head "https://ghcr.io/v2/sidestore/omnisette-server/manifests/latest": unauthorized

### ISSUE THREAD

**Issue by Macleykun** [SideStore/omnisette-server#3]
When pulling the ghcr.io/sidestore/omnisette-server:latest image. I get the following error:
Error response from daemon: Head "https://ghcr.io/v2/sidestore/omnisette-server/manifests/latest": unauthorized
I believe the images are somehow private and can't be publically accessed.

Can you look if the docker image is set to private instead of public?
https://docs.github.com/en/packages/working-with-a-github-packages-registry/working-with-the-container-registry#about-the-container-registry

**Comment by Macleykun** [comment]
can someone check what's set here?
![image](https://github.com/SideStore/omnisette-server/assets/26381427/3e784163-7e89-4f38-b4ef-0089987751bb)

**Comment by Macleykun** [comment]
Perhaps (scrolling more down) you can also link the repo to the package, that might also help with getting it to show up?

**Comment by nythepegasus** [comment]
This should be resolved, I have updated the settings. Please confirm and close this issue if that's the case!

**Comment by Macleykun** [comment]
![image](https://github.com/SideStore/omnisette-server/assets/26381427/5bd9fcb5-8293-4b44-ae59-696570599866)

Thank you guys :D
