### ISSUE TITLE
Unable to Access HTTP Server After Deploying 'omnisette-server' Docker Image on Port 6969

### ISSUE THREAD

**Issue by huweiunique** [SideStore/omnisette-server#7]
Hello, 
   I have deployed the latest version of the 'omnisette-server' Docker image using the command 'docker run -d --restart always --name omnisette -p 6969:80 --volume omnisette_data:/opt/omnisette-server/lib ghcr.io/sidestore/omnisette-server:latest'. However, when I try to access the server via HTTP using the exposed port 6969, I get a 'connection refused' error. Can you please provide guidance on how to properly test the HTTP access to the server after deployment?

**Comment by amsam0** [comment]
Try switching 6969:80 to 80:6969 in the command

**Comment by Macleykun** [comment]
Tested it out:
![image](https://github.com/SideStore/omnisette-server/assets/26381427/87a4fcaa-a6b8-4852-bb9c-81bf390973b3)

It seems to work so i suggest if you still have this issue if your local firewall doesn't allow port 6969 yet!
You can list all listing ports with: sudo lsof -i -P -n | grep LISTEN and see if the 6969 is in there :)
Try to curl it with localhost:6969, then with the host ip and lastly from the place you want to reach it on
